version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    restart: unless-stopped
    network_mode: "host"

    volumes:
      # Aapki 4.9T SSD ka path container ke downloads folder se map kar diya hai
      - /data/downloads:/usr/src/app/downloads

    environment:
      # Bot ko batane ke liye ki downloads isi folder me karne hain
      - DOWNLOAD_DIR=/usr/src/app/downloads/

    env_file:
      - .env
